CREATE TABLE USER (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email varchar(100),
  data MEDIUMTEXT NOT NULL,
  modified_on TIMESTAMP NOT NULL,
  version BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;